server: 
  port: 8989
  
eureka:  
    instance: 
      hostname: localhost 
    client: 
      register-with-eureka: true
      fetch-registry: true 
      serviceUrl: 
         defaultZone: http://localhost:8761/eureka/
      
Spring:
  application:
    name: GATWAY-SERVICE
  cloud:
    gateway:
      routes:
       - id: order-service
         uri: lb://ORDER-SERVICE
         predicates:
          - Path=/order/**
          
       - id: payment-service
         uri: lb://PAYMENT-SERVICE
         predicates:
          - Path=/payment/** 
          
       - id: eureka-cleint-1
         uri: lb://EUREKA-CLIENT-1
         predicates:
          - Path=/client/**
          
       - id: eureka-cleint-2
         uri: lb://EUREKA-CLIENT-2
         predicates:
          - Path=/client2/**   
          
       - id: eureka-cleint-3
         uri: lb://EUREKA-CLIENT-3
         predicates:
          - Path=/client3/**             